title: Installing Python packages with Thonny
hero_image: images/banner.png
description: thonny-install-package description
version: 4
listed: false
copyedit: false
last_tested: "2022-04-26"
steps:
  - title: Introduction
